kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: roboshop-ebs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-03faeb8660845fedd
  directoryPerms: "700"
  basePath: "/roboshop"