apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
    purpose: statefullset-demo
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
    purpose: statefullset-demo
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    purpose: statefullset-demo
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: nginx
    purpose: statefullset-demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx-headless"
  replicas: 4 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
        purpose: statefullset-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi